// <auto-generated />
using System;
using LibraryPenaltyCalculation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LibraryPenaltyCalculation.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220109153947_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LibraryPenaltyCalculation.Core.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Weekend")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weekend2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Currency = "₺",
                            Name = "Turkey",
                            Weekend = "Saturday",
                            Weekend2 = "Sunday"
                        },
                        new
                        {
                            Id = 2,
                            Currency = "د.إ",
                            Name = "Dubai",
                            Weekend = "Friday",
                            Weekend2 = "Saturday"
                        },
                        new
                        {
                            Id = 3,
                            Currency = "$",
                            Name = "United States",
                            Weekend = "Saturday",
                            Weekend2 = "Sunday"
                        });
                });

            modelBuilder.Entity("LibraryPenaltyCalculation.Core.Models.NationalHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("HolidayName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("NationalHolidays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Date = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Yılbaşı"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Date = new DateTime(2022, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Ulusal Egemenlik ve Çocuk Bayramı"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            Date = new DateTime(2022, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Emek ve Dayanışma Günü"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            Date = new DateTime(2022, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Ramazan Bayramı"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 1,
                            Date = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Ramazan Bayramı"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 1,
                            Date = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Ramazan Bayramı"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 1,
                            Date = new DateTime(2022, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Atatürk'ü Anma, Gençlik ve Spor Bayramı"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 1,
                            Date = new DateTime(2022, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Kurban Bayramı"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 1,
                            Date = new DateTime(2022, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Kurban Bayramı"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 1,
                            Date = new DateTime(2022, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Kurban Bayramı"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 1,
                            Date = new DateTime(2022, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Kurban Bayramı"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 1,
                            Date = new DateTime(2022, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Demokrasi Bayramı"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 1,
                            Date = new DateTime(2022, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Zafer Bayramı"
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 1,
                            Date = new DateTime(2022, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Cumhuriyet Bayramı"
                        },
                        new
                        {
                            Id = 15,
                            CountryId = 2,
                            Date = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Yılbaşı"
                        },
                        new
                        {
                            Id = 17,
                            CountryId = 2,
                            Date = new DateTime(2022, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Peygamberin Yükselişi"
                        },
                        new
                        {
                            Id = 18,
                            CountryId = 2,
                            Date = new DateTime(2022, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Mart Ekinoksu"
                        },
                        new
                        {
                            Id = 19,
                            CountryId = 2,
                            Date = new DateTime(2022, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Ramazan Bayramı"
                        },
                        new
                        {
                            Id = 20,
                            CountryId = 2,
                            Date = new DateTime(2022, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Ramazan Bayramı"
                        },
                        new
                        {
                            Id = 21,
                            CountryId = 2,
                            Date = new DateTime(2022, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Ramazan Bayramı"
                        },
                        new
                        {
                            Id = 22,
                            CountryId = 2,
                            Date = new DateTime(2022, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Kurban Bayramı"
                        },
                        new
                        {
                            Id = 23,
                            CountryId = 2,
                            Date = new DateTime(2022, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Kurban Bayramı"
                        },
                        new
                        {
                            Id = 24,
                            CountryId = 2,
                            Date = new DateTime(2022, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Kurban Bayramı"
                        },
                        new
                        {
                            Id = 25,
                            CountryId = 2,
                            Date = new DateTime(2022, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Kurban Bayramı"
                        },
                        new
                        {
                            Id = 26,
                            CountryId = 2,
                            Date = new DateTime(2022, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Hac Mevsimi Başlıyor"
                        },
                        new
                        {
                            Id = 27,
                            CountryId = 2,
                            Date = new DateTime(2022, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Eylül Ekinoksu"
                        },
                        new
                        {
                            Id = 28,
                            CountryId = 2,
                            Date = new DateTime(2022, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Anma Günü"
                        },
                        new
                        {
                            Id = 29,
                            CountryId = 2,
                            Date = new DateTime(2022, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Ulusal Günü"
                        },
                        new
                        {
                            Id = 30,
                            CountryId = 2,
                            Date = new DateTime(2022, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Aralık Gün Dönümü"
                        },
                        new
                        {
                            Id = 31,
                            CountryId = 3,
                            Date = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Yılbaşı"
                        },
                        new
                        {
                            Id = 32,
                            CountryId = 3,
                            Date = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Noel"
                        },
                        new
                        {
                            Id = 33,
                            CountryId = 3,
                            Date = new DateTime(2022, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Şükran Günü"
                        },
                        new
                        {
                            Id = 34,
                            CountryId = 3,
                            Date = new DateTime(2022, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Ulusal Bağımsızlık günü"
                        },
                        new
                        {
                            Id = 35,
                            CountryId = 3,
                            Date = new DateTime(2022, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Martin Luther King Günü"
                        },
                        new
                        {
                            Id = 36,
                            CountryId = 3,
                            Date = new DateTime(2022, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Başkan’nın Günü"
                        },
                        new
                        {
                            Id = 37,
                            CountryId = 3,
                            Date = new DateTime(2022, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Şehitler Günü"
                        },
                        new
                        {
                            Id = 38,
                            CountryId = 3,
                            Date = new DateTime(2022, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "İşçi Bayramı"
                        },
                        new
                        {
                            Id = 39,
                            CountryId = 3,
                            Date = new DateTime(2022, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Colombus Günü"
                        },
                        new
                        {
                            Id = 40,
                            CountryId = 3,
                            Date = new DateTime(2022, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Veterans (Armistice) Günü"
                        });
                });

            modelBuilder.Entity("LibraryPenaltyCalculation.Core.Models.NationalHoliday", b =>
                {
                    b.HasOne("LibraryPenaltyCalculation.Core.Models.Country", "Country")
                        .WithMany("NationalHolidays")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("LibraryPenaltyCalculation.Core.Models.Country", b =>
                {
                    b.Navigation("NationalHolidays");
                });
#pragma warning restore 612, 618
        }
    }
}
